export const TreeData = [
  {
    id: 1103171,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103169,
        parentId: 1103171,
        selected: false,
        children: [
          {
            id: 1103179,
            parentId: 1103169,
            selected: false,
            children: [],
            icon: null,
            name: '表单选课列表',
            url: null,
            permission: 'form:item_setmeal:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103180,
            parentId: 1103169,
            selected: false,
            children: [],
            icon: null,
            name: '添加表单选课',
            url: null,
            permission: 'form:item_setmeal:add',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103181,
            parentId: 1103169,
            selected: false,
            children: [],
            icon: null,
            name: '表单选课编辑',
            url: null,
            permission: 'form:item_setmeal:update',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '表单选课',
        url: '/app/selecourse/formselecourse',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103172,
        parentId: 1103171,
        selected: false,
        children: [
          {
            id: 1103188,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '创建套餐',
            url: null,
            permission: 'setmeal:create',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103189,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '查询套餐详情',
            url: null,
            permission: 'setmeal:query',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103190,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '条件查询套餐列表',
            url: null,
            permission: 'setmeal:list:condition',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103191,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '查询所有套餐',
            url: null,
            permission: 'setmeal:list:all',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103192,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '编辑套餐',
            url: null,
            permission: 'setmeal:edit',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103193,
            parentId: 1103172,
            selected: false,
            children: [],
            icon: null,
            name: '删除套餐',
            url: null,
            permission: 'setmeal:delete',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '课程套餐',
        url: '/app/selecourse/coursesetmealad',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103173,
        parentId: 1103171,
        selected: false,
        children: [
          {
            id: 1103182,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '创建课程内容',
            url: null,
            permission: 'setmeal:coursecontent:create',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103183,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '单个查询课程内容详情',
            url: null,
            permission: 'setmeal:coursecontent:query',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103184,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '修改课程内容',
            url: null,
            permission: 'setmeal:coursecontent:update',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103185,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '删除课程内容',
            url: null,
            permission: 'setmeal:coursecontent:delete',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103186,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '分页查询课程内容',
            url: null,
            permission: 'setmeal:coursecontent:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103187,
            parentId: 1103173,
            selected: false,
            children: [],
            icon: null,
            name: '根据学科和业务线查询课程内容',
            url: null,
            permission: 'setmeal:coursecontent:find:subid:groupid',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '课程内容',
        url: '/app/selecourse/coursecontentad',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103198,
        parentId: 1103171,
        selected: false,
        children: [],
        icon: null,
        name: '学员套餐',
        url: '/app/selecourse/setmealad',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'MergeCellsOutlined',
    name: '套餐管理',
    url: null,
    permission: null,
    type: 1,
    sort: 0,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 1,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 2,
        parentId: 1,
        selected: false,
        children: [
          {
            id: 2001,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '创建文章',
            url: null,
            permission: 'interactive:main:create_article',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2002,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '创建多图文',
            url: null,
            permission: 'interactive:main:create_article_image',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2003,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '创建 h5',
            url: null,
            permission: 'interactive:main:create_h5',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2004,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '创建社交图片',
            url: null,
            permission: 'interactive:main:create_socail_image',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2005,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '上传文件',
            url: null,
            permission: 'interactive:main:upload',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2006,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '创建链接',
            url: null,
            permission: 'interactive:main:create_link',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2007,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '公众号群发',
            url: null,
            permission: 'interactive:main:send_official_account_group',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2008,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '公众号自动推送',
            url: null,
            permission: 'interactive:main:official_account_auto_push',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2009,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '活动二维码',
            url: null,
            permission: 'interactive:main:activity_qrcode',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2010,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '粉丝推广计划',
            url: null,
            permission: 'interactive:main:fans_promation_plan',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2011,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '微信打卡',
            url: null,
            permission: 'interactive:main:weixin_sign',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2012,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '发起邮件群发',
            url: null,
            permission: 'interactive:main:send_group_email',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 2013,
            parentId: 2,
            selected: false,
            children: [],
            icon: null,
            name: '直播间',
            url: null,
            permission: 'interactive:main:broadcast',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '交互管理',
        url: '/app/operate/interactive',
        permission: null,
        type: 1,
        sort: 2,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 3,
        parentId: 1,
        selected: false,
        children: [
          {
            id: 3001,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '新粉丝',
            url: null,
            permission: 'wechat_public:new_fans:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3002,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '关键词',
            url: null,
            permission: 'wechat_public:keyword:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3003,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '兴趣标签',
            url: null,
            permission: 'wechat_public:intest:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3004,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '定时计划',
            url: null,
            permission: 'wechat_public:timing_plan:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3005,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '拍照小程序',
            url: null,
            permission: 'wechat_public:photo_applet:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3006,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '活动二维码',
            url: null,
            permission: 'wechat_public:activity_qrcode:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3007,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '推广计划',
            url: null,
            permission: 'wechat_public:promation_plan:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3008,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '推广计划推广图',
            url: null,
            permission: 'wechat_public:promation_plan_image:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 3009,
            parentId: 3,
            selected: false,
            children: [],
            icon: null,
            name: '行为推送',
            url: null,
            permission: 'wechat_public:action_push_configure:view',
            type: 2,
            sort: 7,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '公众号交互规则',
        url: '/app/operate/officialAccounts',
        permission: null,
        type: 1,
        sort: 3,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'DotChartOutlined',
    name: '运营管理',
    url: '',
    permission: null,
    type: 1,
    sort: 1,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 4,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 5,
        parentId: 4,
        selected: false,
        children: [],
        icon: null,
        name: '通话历史',
        url: '/app/sales/history/call',
        permission: null,
        type: 1,
        sort: 5,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 6,
        parentId: 4,
        selected: false,
        children: [],
        icon: null,
        name: '链接管理',
        url: '/app/operate/links',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 7,
        parentId: 4,
        selected: false,
        children: [],
        icon: null,
        name: '公众号群发历史',
        url: '/app/operate/officialAccountGroupSendHistory',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'ToolOutlined',
    name: '质检管理',
    url: null,
    permission: null,
    type: 1,
    sort: 4,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 8,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103145,
        parentId: 8,
        selected: false,
        children: [],
        icon: null,
        name: '媒体管理',
        url: '/app/qrcode/media',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103216,
        parentId: 8,
        selected: false,
        children: [
          {
            id: 1103217,
            parentId: 1103216,
            selected: false,
            children: [],
            icon: null,
            name: '投放媒体管理',
            url: '/app/delivery/deliveryMedia',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103218,
            parentId: 1103216,
            selected: false,
            children: [],
            icon: null,
            name: '代理商管理',
            url: '/app/delivery/agent',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 12,
            parentId: 1103216,
            selected: false,
            children: [],
            icon: null,
            name: '落地页管理',
            url: '/app/delivery/Landing',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: '',
        name: '信息流管理',
        url: null,
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 10,
        parentId: 8,
        selected: false,
        children: [
          {
            id: 11,
            parentId: 10,
            selected: false,
            children: [],
            icon: null,
            name: '媒体管理',
            url: '/app/delivery/kol/media',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103212,
            parentId: 10,
            selected: false,
            children: [],
            icon: null,
            name: '投放排期',
            url: '/app/delivery/kol/schedule',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103213,
            parentId: 10,
            selected: false,
            children: [],
            icon: null,
            name: '投放管理',
            url: '/app/delivery/kol/delivery',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103214,
            parentId: 10,
            selected: false,
            children: [],
            icon: null,
            name: '落地页管理',
            url: '/app/delivery/kol/landingPage',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: 'KOL管理',
        url: null,
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 13,
        parentId: 8,
        selected: false,
        children: [],
        icon: null,
        name: '模版管理',
        url: '/app/delivery/Template',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 2014,
        parentId: 8,
        selected: false,
        children: [],
        icon: null,
        name: '投放数据展示',
        url: '/app/delivery/deliveryData',
        permission: '/app/delivery/deliveryData\n',
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'TransactionOutlined',
    name: '投放管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 14,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 15,
        parentId: 14,
        selected: false,
        children: [
          {
            id: 1103127,
            parentId: 15,
            selected: false,
            children: [],
            icon: null,
            name: '营销中心-接量组管理',
            url: null,
            permission: 'marketing:media:receive:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '接量组管理',
        url: '/app/qrcode/accept/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 16,
        parentId: 14,
        selected: false,
        children: [
          {
            id: 1103128,
            parentId: 16,
            selected: false,
            children: [],
            icon: null,
            name: '营销中心-表单分量',
            url: null,
            permission: 'marketing:media:receive:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '表单分量',
        url: '/app/qrcode/formDistribution/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 17,
        parentId: 14,
        selected: false,
        children: [
          {
            id: 1103125,
            parentId: 17,
            selected: false,
            children: [],
            icon: null,
            name: '预约量管理',
            url: null,
            permission: 'marketing:overpoint:index',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '预约量管理',
        url: '/app/overpoint/index',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'RiseOutlined',
    name: '流量分发',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 18,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 19,
        parentId: 18,
        selected: false,
        children: [
          {
            id: 19001,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '资料浏览',
            url: null,
            permission: 'customer_detail:dynamic:viewfile',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19002,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '资料发送',
            url: null,
            permission: 'customer_detail:dynamic:sendfile',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19003,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '通话记录',
            url: null,
            permission: 'customer_detail:dynamic:phone_record',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19004,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '远程演示',
            url: null,
            permission: 'customer_detail:dynamic:remote',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19005,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '关注的微信公众号',
            url: null,
            permission: 'customer_detail:dynamic:weixin',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19006,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '发送资料',
            url: null,
            permission: 'customer_detail:dynamic:sendfile',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 19007,
            parentId: 19,
            selected: false,
            children: [],
            icon: null,
            name: '发起通话',
            url: null,
            permission: 'customer_detail:dynamic:call',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '客户管理',
        url: '/app/customer',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 20,
        parentId: 18,
        selected: false,
        children: [
          {
            id: 20001,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '搜索按钮',
            url: null,
            permission: 'crowd:search_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20002,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '添加按钮',
            url: null,
            permission: 'crowd:add_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20003,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '分享按钮',
            url: null,
            permission: 'crowd:share_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20004,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '复制按钮',
            url: null,
            permission: 'crowd:copy_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20005,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '编辑按钮',
            url: null,
            permission: 'crowd:edit_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20006,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '删除按钮',
            url: null,
            permission: 'crowd:delete_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 20007,
            parentId: 20,
            selected: false,
            children: [],
            icon: null,
            name: '查看表单',
            url: null,
            permission: 'crowd:view_form_data_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '客户分群',
        url: '/app/customer/swarm',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 21,
        parentId: 18,
        selected: false,
        children: [],
        icon: null,
        name: '自定义菜单',
        url: '/app/customer/personalMenu',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'UsergroupAddOutlined',
    name: '客户管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 22,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 23,
        parentId: 22,
        selected: false,
        children: [
          {
            id: 23001,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '搜索按钮',
            url: null,
            permission: 'files:search_buttion:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23002,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '添加按钮',
            url: null,
            permission: 'files:add_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23003,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '分享按钮',
            url: null,
            permission: 'files:share_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23004,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '资料发送按钮',
            url: null,
            permission: 'files:send_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23005,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '资料编辑按钮',
            url: null,
            permission: 'files:edit_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23006,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '资料删除按钮',
            url: null,
            permission: 'files:delete_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23007,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '资料下载按钮',
            url: null,
            permission: 'files:download_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 23008,
            parentId: 23,
            selected: false,
            children: [],
            icon: null,
            name: '查看表单数据',
            url: null,
            permission: 'files:view_form_data_button:view',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '资料库',
        url: '/app/file/files',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 24,
        parentId: 22,
        selected: false,
        children: [],
        icon: null,
        name: '话术管理',
        url: '/app/description/menege',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 25,
        parentId: 22,
        selected: false,
        children: [
          {
            id: 1103099,
            parentId: 25,
            selected: false,
            children: [],
            icon: null,
            name: '营销中心-素材管理',
            url: null,
            permission: 'marketing:template:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '素材管理',
        url: '/app/qrcode/resources',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 26,
        parentId: 22,
        selected: false,
        children: [],
        icon: null,
        name: '标签管理',
        url: '/app/file-management-tags/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'RestOutlined',
    name: '营销物料',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 27,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103206,
        parentId: 27,
        selected: false,
        children: [],
        icon: null,
        name: '我的营销号',
        url: '/app/marketNum/myMarketNum',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 28,
        parentId: 27,
        selected: false,
        children: [
          {
            id: 29,
            parentId: 28,
            selected: false,
            children: [],
            icon: null,
            name: '设备管理',
            url: '/app/marketNum/device',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 30,
            parentId: 28,
            selected: false,
            children: [
              {
                id: 1103079,
                parentId: 30,
                selected: false,
                children: [],
                icon: null,
                name: '营销号管理',
                url: null,
                permission: 'marketing:system:seller:manage',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
            ],
            icon: null,
            name: '营销号管理',
            url: '/app/marketNum/manage',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '营销号管理',
        url: null,
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'ShoppingOutlined',
    name: '营销资产',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 31,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103194,
        parentId: 31,
        selected: false,
        children: [
          {
            id: 1103195,
            parentId: 1103194,
            selected: false,
            children: [],
            icon: null,
            name: '短信工具',
            url: '/app/messageRobot/list',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: '',
        name: '短信机器人',
        url: null,
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 32,
        parentId: 31,
        selected: false,
        children: [],
        icon: null,
        name: '小A机器人',
        url: '/app/robot',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 33,
        parentId: 31,
        selected: false,
        children: [
          {
            id: 34,
            parentId: 33,
            selected: false,
            children: [
              {
                id: 1103137,
                parentId: 34,
                selected: false,
                children: [],
                icon: null,
                name: '钉钉机器人-机器人管理',
                url: null,
                permission: 'marketing:dingtalk:robot:manage',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
            ],
            icon: null,
            name: '机器人管理',
            url: '/app/dtrobot/robotlist',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 35,
            parentId: 33,
            selected: false,
            children: [
              {
                id: 1103138,
                parentId: 35,
                selected: false,
                children: [],
                icon: null,
                name: '钉钉机器人-推送策略',
                url: null,
                permission: 'marketing:dingtalk:robot:manage',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
            ],
            icon: null,
            name: '推送策略',
            url: '/app/dtrobot/strategylist',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 36,
            parentId: 33,
            selected: false,
            children: [
              {
                id: 1103139,
                parentId: 36,
                selected: false,
                children: [],
                icon: null,
                name: '钉钉机器人-消息管理',
                url: null,
                permission: 'marketing:dingtalk:robot:manage',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
            ],
            icon: null,
            name: '消息管理',
            url: '/app/dtrobot/messagelist',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '钉钉机器人',
        url: null,
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'PushpinOutlined',
    name: '营销工具',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 37,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103158,
        parentId: 37,
        selected: false,
        children: [
          {
            id: 1103159,
            parentId: 1103158,
            selected: false,
            children: [],
            icon: null,
            name: '盲盒概览',
            url: '/app/blindBox/overview',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103160,
            parentId: 1103158,
            selected: false,
            children: [],
            icon: null,
            name: '盲盒资源',
            url: '/app/blindBox/resourceManage',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103161,
            parentId: 1103158,
            selected: false,
            children: [],
            icon: null,
            name: '领取渠道',
            url: '/app/blindBox/channelManage',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103162,
            parentId: 1103158,
            selected: false,
            children: [],
            icon: null,
            name: '用户参与详情',
            url: '/app/blindBox/receive',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103174,
            parentId: 1103158,
            selected: false,
            children: [],
            icon: null,
            name: '直播盲盒',
            url: '/app/blindBox/activity',
            permission: null,
            type: 1,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: '',
        name: '盲盒活动',
        url: null,
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 38,
        parentId: 37,
        selected: false,
        children: [
          {
            id: 39,
            parentId: 38,
            selected: false,
            children: [],
            icon: null,
            name: '转介绍',
            url: '/app/activity/activityList',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 40,
            parentId: 38,
            selected: false,
            children: [
              {
                id: 1103134,
                parentId: 40,
                selected: false,
                children: [],
                icon: null,
                name: '奖品审核-运营审批通过',
                url: null,
                permission: 'marketing:paycashback:approve',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
              {
                id: 1103136,
                parentId: 40,
                selected: false,
                children: [],
                icon: null,
                name: '奖品审核-运营审批驳回',
                url: null,
                permission: 'marketing:paycashback:reject',
                type: 2,
                sort: 0,
                urlType: 1,
                dflt: 0,
                enabled: 1,
              },
            ],
            icon: null,
            name: '奖品审核',
            url: '/app/qrcode/testimonial/audit',
            permission: null,
            type: 1,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '转介绍活动',
        url: null,
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 41,
        parentId: 37,
        selected: false,
        children: [
          {
            id: 1103126,
            parentId: 41,
            selected: false,
            children: [],
            icon: null,
            name: '红包管理',
            url: null,
            permission: 'marketing:vipcourse:redpack:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '直播红包',
        url: '/app/qrcode/redpack',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103197,
        parentId: 37,
        selected: false,
        children: [
          {
            id: 1103199,
            parentId: 1103197,
            selected: false,
            children: [],
            icon: null,
            name: '编辑直播货架',
            url: null,
            permission: 'marketing:shelves:edit',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103200,
            parentId: 1103197,
            selected: false,
            children: [],
            icon: null,
            name: '直播货架列表',
            url: null,
            permission: 'marketing:shelves:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103201,
            parentId: 1103197,
            selected: false,
            children: [],
            icon: null,
            name: '添加直播货架',
            url: null,
            permission: 'marketing:shelves:add',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '直播货架',
        url: '/app/goodsShelves/shelvesList',
        permission: null,
        type: 1,
        sort: 7,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'GiftOutlined',
    name: '营销活动',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 42,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103157,
        parentId: 42,
        selected: false,
        children: [
          {
            id: 1103165,
            parentId: 1103157,
            selected: false,
            children: [],
            icon: null,
            name: '组合商品列表',
            url: null,
            permission: 'marketing:item_group:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103166,
            parentId: 1103157,
            selected: false,
            children: [],
            icon: null,
            name: '添加组合商品',
            url: null,
            permission: 'marketing:item_group:add',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103167,
            parentId: 1103157,
            selected: false,
            children: [],
            icon: null,
            name: '组合商品详情',
            url: null,
            permission: 'marketing:item_group:info',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103168,
            parentId: 1103157,
            selected: false,
            children: [],
            icon: null,
            name: '组合商品编辑',
            url: null,
            permission: 'marketing:item_group:update',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '组合商品',
        url: '/app/goods/combined',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103170,
        parentId: 42,
        selected: false,
        children: [
          {
            id: 1103175,
            parentId: 1103170,
            selected: false,
            children: [],
            icon: null,
            name: '大课畅学卡商品列表',
            url: null,
            permission: 'marketing:vipcourse:bigcard:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103176,
            parentId: 1103170,
            selected: false,
            children: [],
            icon: null,
            name: '添加大课畅学卡',
            url: null,
            permission: 'marketing:vipcourse:bigcard:save',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103177,
            parentId: 1103170,
            selected: false,
            children: [],
            icon: null,
            name: '大课畅学卡详情',
            url: null,
            permission: 'marketing:vipcourse:bigcard:info',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103178,
            parentId: 1103170,
            selected: false,
            children: [],
            icon: null,
            name: '大课畅学卡编辑',
            url: null,
            permission: 'marketing:vipcourse:bigcard:update',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '畅学卡商品管理',
        url: '/app/goods/changlearn',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 43,
        parentId: 42,
        selected: false,
        children: [
          {
            id: 1103087,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'vip课程管理',
            url: null,
            permission: 'marketing:vipcourse:manager',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103088,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'vip课程-列表查看',
            url: null,
            permission: 'marketing:vipcourse:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103089,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'vip课程-操作',
            url: null,
            permission: 'marketing:vipcourse:operation',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103090,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-班次-新建&编辑',
            url: null,
            permission: 'marketing:vipcourse:class:manager',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103091,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-班次-查看',
            url: null,
            permission: 'marketing:vipcourse:class:info',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103092,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-推广渠道创建',
            url: null,
            permission: 'marketing:vipcourse:channel:manager',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103093,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-渠道-1销量图表',
            url: null,
            permission: 'marketing:vipcourse:channel:table',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103094,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-渠道-2详细数据',
            url: null,
            permission: 'marketing:vipcourse:channel:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103095,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-销售-1销售图表',
            url: null,
            permission: 'marketing:vipcourse:sales:table',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103096,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课程-销售-2详细数据',
            url: null,
            permission: 'marketing:vipcourse:sales:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103113,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'VIP课-销售额',
            url: null,
            permission: 'marketing:vipcourse:sales',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103124,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: 'vip课程-编辑',
            url: null,
            permission: 'marketing:vipcourse:edit',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43001,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '查询',
            url: null,
            permission: 'vipcourse:list:query',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43002,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '新建课程',
            url: null,
            permission: 'vipcourse:list:new_course',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43003,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '编辑课程',
            url: null,
            permission: 'vipcourse:list:edit_course',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43004,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '查看班次',
            url: null,
            permission: 'vipcourse:list:view_class',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43005,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '查询课程销售',
            url: null,
            permission: 'vipcourse:list:view_salse',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43006,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '查询课程渠道',
            url: null,
            permission: 'vipcourse:list:view_channel',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 43007,
            parentId: 43,
            selected: false,
            children: [],
            icon: null,
            name: '查询投放渠道',
            url: null,
            permission: 'vipcourse:list:view_delivery',
            type: 2,
            sort: 6,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '正价课商品',
        url: '/app/goods/courseList',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 44,
        parentId: 42,
        selected: false,
        children: [],
        icon: null,
        name: '体验课商品',
        url: '/app/goods/courseList/1',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 45,
        parentId: 42,
        selected: false,
        children: [
          {
            id: 1103146,
            parentId: 45,
            selected: false,
            children: [],
            icon: null,
            name: '新公开课创建',
            url: null,
            permission: 'marketing:vipcourse:opencourse:info',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '公开课商品',
        url: '/app/opencourse/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103069,
        parentId: 42,
        selected: false,
        children: [],
        icon: null,
        name: '新公开课',
        url: '/app/newopencourse/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'CodepenOutlined',
    name: '商品管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 46,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 47,
        parentId: 46,
        selected: false,
        children: [
          {
            id: 1103105,
            parentId: 47,
            selected: false,
            children: [],
            icon: null,
            name: '订单中心-订单列表',
            url: null,
            permission: 'marketing:ordercenter:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '订单列表',
        url: '/app/order',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 48,
        parentId: 46,
        selected: false,
        children: [
          {
            id: 1103106,
            parentId: 48,
            selected: false,
            children: [],
            icon: null,
            name: '订单中心-退款记录',
            url: null,
            permission: 'marketing:ordercenter:refund',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '退款记录',
        url: '/app/refund',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'FileDoneOutlined',
    name: '订单管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 49,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 50,
        parentId: 49,
        selected: false,
        children: [
          {
            id: 1103107,
            parentId: 50,
            selected: false,
            children: [],
            icon: null,
            name: '收款管理',
            url: null,
            permission: 'marketing:finance:payment',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '收款管理',
        url: '/app/finance/payment',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 51,
        parentId: 49,
        selected: false,
        children: [
          {
            id: 1103108,
            parentId: 51,
            selected: false,
            children: [],
            icon: null,
            name: '退款管理',
            url: null,
            permission: 'marketing:finance:refund',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '退款管理',
        url: '/app/finance/refund',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 52,
        parentId: 49,
        selected: false,
        children: [
          {
            id: 1103109,
            parentId: 52,
            selected: false,
            children: [],
            icon: null,
            name: '发票管理',
            url: null,
            permission: 'marketing:finance:bill',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '发票管理',
        url: '/app/finance/bill',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 53,
        parentId: 49,
        selected: false,
        children: [
          {
            id: 1103129,
            parentId: 53,
            selected: false,
            children: [],
            icon: null,
            name: '返现管理-列表',
            url: null,
            permission: 'marketing:paycashback:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103135,
            parentId: 53,
            selected: false,
            children: [],
            icon: null,
            name: '奖品审核-运营批量审批通过',
            url: null,
            permission: 'marketing:paycashback:cashbackbatchapprove',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '返现管理',
        url: '/app/finance/cashback',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103219,
        parentId: 49,
        selected: false,
        children: [],
        icon: null,
        name: '售后管理',
        url: '/app/finance/aftermarketad',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'PoundCircleOutlined',
    name: '财务管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 54,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 55,
        parentId: 54,
        selected: false,
        children: [
          {
            id: 1103140,
            parentId: 55,
            selected: false,
            children: [],
            icon: null,
            name: '合同管理-合同列表',
            url: '',
            permission: 'marketing:contract:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '合同列表',
        url: '/app/contract/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 56,
        parentId: 54,
        selected: false,
        children: [
          {
            id: 1103141,
            parentId: 56,
            selected: false,
            children: [],
            icon: null,
            name: '合同管理-合同模板',
            url: '',
            permission: 'marketing:contract:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '合同模板',
        url: '/app/contract/template/list',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'ProfileOutlined',
    name: '合同管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 57,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103151,
        parentId: 57,
        selected: false,
        children: [],
        icon: null,
        name: '查询日志',
        url: null,
        permission: 'marketing:checkin:log',
        type: 0,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 58,
        parentId: 57,
        selected: false,
        children: [
          {
            id: 1103148,
            parentId: 58,
            selected: false,
            children: [],
            icon: null,
            name: '打卡计划管理-查询',
            url: null,
            permission: 'marketing:checkin:plan',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '打卡计划管理',
        url: '/app/checkin/plan',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 59,
        parentId: 57,
        selected: false,
        children: [],
        icon: null,
        name: '打卡点管理',
        url: '/app/checkin/point',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103147,
        parentId: 57,
        selected: false,
        children: [],
        icon: null,
        name: '操作日志',
        url: '/app/checkin/punchlog',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'ShakeOutlined',
    name: '打卡管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 72,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103156,
        parentId: 72,
        selected: false,
        children: [],
        icon: null,
        name: '课程直播监控',
        url: '/app/dataBI/liveList',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103203,
        parentId: 72,
        selected: false,
        children: [],
        icon: null,
        name: '营销直播监控',
        url: '/app/livingwatch/watch',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'DashboardOutlined',
    name: '直播管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 1103142,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103149,
        parentId: 1103142,
        selected: false,
        children: [],
        icon: null,
        name: '创建授权课程',
        url: null,
        permission: 'marketing:learning:vipcourses',
        type: 0,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103150,
        parentId: 1103142,
        selected: false,
        children: [],
        icon: null,
        name: '学情数据列表',
        url: null,
        permission: 'marketing:learning:learningLogs',
        type: 0,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103143,
        parentId: 1103142,
        selected: false,
        children: [],
        icon: null,
        name: '课程授权管理',
        url: '/app/learning/courseAuthorization',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 1103144,
        parentId: 1103142,
        selected: false,
        children: [],
        icon: null,
        name: '学情数据',
        url: '/app/learning/learningSituation',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'SaveOutlined',
    name: '学情管理',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 1103210,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 1103211,
        parentId: 1103210,
        selected: false,
        children: [],
        icon: null,
        name: '下载列表',
        url: '/app/docDownload/downloadList',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'DashboardOutlined',
    name: '文档下载',
    url: null,
    permission: null,
    type: 1,
    sort: 6,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 70,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 71,
        parentId: 70,
        selected: false,
        children: [
          {
            id: 1103072,
            parentId: 71,
            selected: false,
            children: [],
            icon: null,
            name: '公开课-管理',
            url: null,
            permission: 'marketing:opencourse:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103073,
            parentId: 71,
            selected: false,
            children: [],
            icon: null,
            name: '公开课-列表&详情-查看',
            url: null,
            permission: 'marketing:opencourse:list',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103074,
            parentId: 71,
            selected: false,
            children: [],
            icon: null,
            name: '公开课-推广渠道及学员情况查看',
            url: null,
            permission: 'marketing:opencourse:student',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103100,
            parentId: 71,
            selected: false,
            children: [],
            icon: null,
            name: '公海流量',
            url: null,
            permission: 'marketing:opencourse:add:allot',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
          {
            id: 1103101,
            parentId: 71,
            selected: false,
            children: [],
            icon: null,
            name: '手动分配流量',
            url: null,
            permission: 'marketing:opencourse:allot',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '公开课列表',
        url: '/app/course/list',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'PlaySquareOutlined',
    name: '公开课',
    url: null,
    permission: null,
    type: 1,
    sort: 98,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 68,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 69,
        parentId: 68,
        selected: false,
        children: [],
        icon: null,
        name: '班级管理',
        url:
          'https://mos2-test.kaikeba.com/app/04bb2ceb-fe0a-4866-870a-4a3b36b8e463/861000',
        permission: null,
        type: 1,
        sort: 0,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'ContainerOutlined',
    name: '班级管理',
    url: null,
    permission: null,
    type: 1,
    sort: 99,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 64,
    parentId: 0,
    selected: false,
    children: [
      {
        id: 65,
        parentId: 64,
        selected: false,
        children: [
          {
            id: 1103076,
            parentId: 65,
            selected: false,
            children: [],
            icon: null,
            name: '帐号管理',
            url: null,
            permission: 'marketing:system:account:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '帐号管理',
        url: '/app/organization/account',
        permission: 'marketing:system:account:manage',
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 66,
        parentId: 64,
        selected: false,
        children: [],
        icon: null,
        name: '部门管理',
        url: '/app/organization/department',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
      {
        id: 67,
        parentId: 64,
        selected: false,
        children: [
          {
            id: 1103077,
            parentId: 67,
            selected: false,
            children: [],
            icon: null,
            name: '角色管理',
            url: null,
            permission: 'marketing:system:role:manage',
            type: 2,
            sort: 0,
            urlType: 1,
            dflt: 0,
            enabled: 1,
          },
        ],
        icon: null,
        name: '角色管理',
        url: '/app/organization/role',
        permission: null,
        type: 1,
        sort: 6,
        urlType: 1,
        dflt: 0,
        enabled: 1,
      },
    ],
    icon: 'UserOutlined',
    name: '组织管理',
    url: null,
    permission: null,
    type: 1,
    sort: 100,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
]

export const TreeList = [
  {
    id: 1103179,
    parentId: 1103169,
    selected: false,
    children: [],
    icon: null,
    name: '表单选课列表',
    url: null,
    permission: 'form:item_setmeal:list',
    type: 2,
    sort: 0,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 1103180,
    parentId: 1103169,
    selected: false,
    children: [],
    icon: null,
    name: '添加表单选课',
    url: null,
    permission: 'form:item_setmeal:add',
    type: 2,
    sort: 0,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
  {
    id: 1103181,
    parentId: 1103169,
    selected: false,
    children: [],
    icon: null,
    name: '表单选课编辑',
    url: null,
    permission: 'form:item_setmeal:update',
    type: 2,
    sort: 0,
    urlType: 1,
    dflt: 0,
    enabled: 1,
  },
]

export default {
  TreeData,
  TreeList,
}
